"use strict";
exports.__esModule = true;
var calc_1 = require("./calc");
var objCalc = new calc_1.Calculator();
console.log(objCalc.add(2, 3));
console.log(objCalc.sub(10, 5));
console.log(objCalc.mul(12, 6));
console.log(objCalc.div(20, 10));
// import { Calculator} from './calc';
// var objCalc = new Calculator();
// console.log(objCalc.add(2,3));
// console.log(objCalc.sub(10, 5));
